### ISSUE TITLE
Specified time is not supported in this calendar. It should be between 0001/1/1 12:00:00 ق.ظ (Gregorian date) and 9378/10/13 11:59:59 ب.ظ (Gregorian date), inclusive. (Parameter 'time')

### ISSUE THREAD

**Issue by Kamalifar** [bitfoundation/bitplatform#3600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

An unhandled exception occurred during I completely erase the value inside a Date Picker. I just upgraded from version 2 to version 4.8. This problem does not exist in version 2.

Suppose you select a date, now if you double-click on the field value and delete it or select it and then delete it with the delete key or backspace, you will face this exception.

My date picker property is as follows:

```razor
<BitDatePicker @bind-Value="Model.RegisterDate"
                                       AllowTextInput="true"
                                       FormatDate="yyyy/MM/dd"
                                       GoToToday="Today" Placeholder="Insert date here"
                                       Culture="PersianCultureHelper.GetFaIrCultureByFarsiNames()"
                                       Style="width:150px; display:inline-block;">
</BitDatePicker>
```

The PersianCultureHelper is as follows:

```cs 
public static class PersianCultureHelper
{
        private static readonly FieldInfo _cultureDataField = typeof(TextInfo).GetField("_cultureData", BindingFlags.NonPublic | BindingFlags.Instance)!;

        private static readonly FieldInfo _iReadingLayoutField = Type.GetType("System.Globalization.CultureData, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e")!.GetField("_iReadingLayout", BindingFlags.NonPublic | BindingFlags.Instance)!;

        public static CultureInfo GetFaIrCultureByFarsiNames()
        {
            var cultureInfo = CultureInfo.CreateSpecificCulture("fa-IR");

            cultureInfo.DateTimeFormat.MonthNames = new[]
            {
            "فروردین", "اردیبهشت", "خرداد", "تیر", "مرداد", "شهریور", "مهر", "آبان", "آذر", "دی", "بهمن", "اسفند", ""
        };

            cultureInfo.DateTimeFormat.AbbreviatedMonthNames = new[]
            {
            "فروردین", "اردیبهشت", "خرداد", "تیر", "مرداد", "شهریور", "مهر", "آبان", "آذر", "دی", "بهمن", "اسفند", ""
        };

            cultureInfo.DateTimeFormat.MonthGenitiveNames = cultureInfo.DateTimeFormat.MonthNames;
            cultureInfo.DateTimeFormat.AbbreviatedMonthGenitiveNames = cultureInfo.DateTimeFormat.AbbreviatedMonthNames;
            cultureInfo.DateTimeFormat.DayNames = new[]
            {
            "یکشنبه", "دوشنبه", "ﺳﻪشنبه", "چهارشنبه", "پنجشنبه", "جمعه", "شنبه"
        };

            cultureInfo.DateTimeFormat.AbbreviatedDayNames = new[]
            {
            "ی", "د", "س", "چ", "پ", "ج", "ش"
        };

            cultureInfo.DateTimeFormat.ShortestDayNames = new[]
            {
            "ی", "د", "س", "چ", "پ", "ج", "ش"
        };

            cultureInfo.DateTimeFormat.AMDesignator = "ق.ظ";
            cultureInfo.DateTimeFormat.PMDesignator = "ب.ظ";
            cultureInfo.DateTimeFormat.ShortDatePattern = "yyyy/MM/dd";
            cultureInfo.DateTimeFormat.FirstDayOfWeek = DayOfWeek.Saturday;

            var cultureData = _cultureDataField.GetValue(cultureInfo.TextInfo);

            _iReadingLayoutField.SetValue(cultureData, 1 /*rtl*/); // this affects cultureInfo.TextInfo.IsRightToLeft

            PersianCalendar cal = new PersianCalendar();

            cultureInfo.DateTimeFormat.Calendar = cal;

            return cultureInfo;
        }
}
```

### Exceptions (if any)

```
System.ArgumentOutOfRangeException: Specified time is not supported in this calendar. It should be between 0001/1/1 12:00:00 ق.ظ (Gregorian date) and 9378/10/13 11:59:59 ب.ظ (Gregorian date), inclusive. (Parameter 'time')
Actual value was 0.
   at System.Globalization.PersianCalendar.CheckTicksRange(Int64 ticks)
   at System.Globalization.PersianCalendar.GetDatePart(Int64 ticks, Int32 part)
   at System.Globalization.PersianCalendar.GetYear(DateTime time)
   at Bit.BlazorUI.BitDatePicker.CheckCurrentCalendarMatchesCurrentValue()
   at Bit.BlazorUI.BitDatePicker.HandleChange(ChangeEventArgs e)
```

### .NET Version

6.0

### Anything else?

windows 10 21H2
visual studio 2022
Blazor server
BitBlazor 4.9pre2 , 4.8

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue or not.

**Comment by msynk** [comment]
Resolving this issue has started. It will be announced when this issue is resolved.

**Comment by msynk** [comment]
The pre-release has been published. Please give it a try and give feedback.
