### ISSUE TITLE
Running Bit v8.10.0-pre-05 Maui project on Android Emulator 10

### ISSUE THREAD

**Issue by mr-farzam** [bitfoundation/bitplatform#8232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Bit.Boilerplate version 8.10.0-pre-05
On Android Emulator 14 it connects to the api, but on Android Emulator 10 it doesn't.
I made a new version of Android 10 with default settings, it wouldn't connect again, and when signing in, it shows this error in the console:
Project1.Client.Core.Services.ExceptionHandlerBase: Error: Microsoft.JSInterop.JSException: Could not find 'BitBlazorUI.Utils.setProperty' ('BitBlazorUI' was undefined).
at https://0.0.0.0/_framework/blazor.webview.js:1:540

### Expected Behavior

```
[0:] Project1.Client.Core.Services.ExceptionHandlerBase: Error: Microsoft.JSInterop.JSException: Could not find 'BitBlazorUI.Utils.setProperty' ('BitBlazorUI' was undefined).
Error: Could not find 'BitBlazorUI.Utils.setProperty' ('BitBlazorUI' was undefined).
    at https://0.0.0.0/_framework/blazor.webview.js:1:540
    at Array.forEach (<anonymous>)
    at l.findFunction (https://0.0.0.0/_framework/blazor.webview.js:1:508)
    at w (https://0.0.0.0/_framework/blazor.webview.js:1:5251)
    at https://0.0.0.0/_framework/blazor.webview.js:1:3044
    at new Promise (<anonymous>)
    at g.beginInvokeJSFromDotNet (https://0.0.0.0/_framework/blazor.webview.js:1:3007)
    at External.__callback (https://0.0.0.0/_framework/blazor.webview.js:1:48020)
    at MessagePort.<anonymous> (<anonymous>:23:21)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Bit.BlazorUI.BitCheckbox.OnParametersSetAsync() in /home/runner/work/bitplatform/bitplatform/src/BlazorUI/Bit.BlazorUI/Components/Inputs/Checkbox/BitCheckbox.razor.cs:line 129
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

Microsoft.JSInterop.JSException: Could not find 'BitBlazorUI.Utils.setProperty' ('BitBlazorUI' was undefined).
Error: Could not find 'BitBlazorUI.Utils.setProperty' ('BitBlazorUI' was undefined).
    at https://0.0.0.0/_framework/blazor.webview.js:1:540
    at Array.forEach (<anonymous>)
    at l.findFunction (https://0.0.0.0/_framework/blazor.webview.js:1:508)
    at w (https://0.0.0.0/_framework/blazor.webview.js:1:5251)
    at https://0.0.0.0/_framework/blazor.webview.js:1:3044
    at new Promise (<anonymous>)
    at g.beginInvokeJSFromDotNet (https://0.0.0.0/_framework/blazor.webview.js:1:3007)
    at External.__callback (https://0.0.0.0/_framework/blazor.webview.js:1:48020)
    at MessagePort.<anonymous> (<anonymous>:23:21)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Bit.BlazorUI.BitCheckbox.OnParametersSetAsync() in /home/runner/work/bitplatform/bitplatform/src/BlazorUI/Bit.BlazorUI/Components/Inputs/Checkbox/BitCheckbox.razor.cs:line 129
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
[DOTNET] fail: Project1.Client.Core.Services.ExceptionHandlerBase[0]
[DOTNET]       Microsoft.JSInterop.JSException: Could not find 'BitBlazorUI.Utils.setProperty' ('BitBlazorUI' was undefined).
[DOTNET]       Error: Could not find 'BitBlazorUI.Utils.setProperty' ('BitBlazorUI' was undefined).
[DOTNET]           at https://0.0.0.0/_framework/blazor.webview.js:1:540
[DOTNET]           at Array.forEach (<anonymous>)
[DOTNET]           at l.findFunction (https://0.0.0.0/_framework/blazor.webview.js:1:508)
[DOTNET]           at w (https://0.0.0.0/_framework/blazor.webview.js:1:5251)
[DOTNET]           at https://0.0.0.0/_framework/blazor.webview.js:1:3044
[DOTNET]           at new Promise (<anonymous>)
[DOTNET]           at g.beginInvokeJSFromDotNet (https://0.0.0.0/_framework/blazor.webview.js:1:3007)
[DOTNET]           at External.__callback (https://0.0.0.0/_framework/blazor.webview.js:1:48020)
[DOTNET]           at MessagePort.<anonymous> (<anonymous>:23:21)
[DOTNET]          at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
[DOTNET]          at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
[DOTNET]          at Bit.BlazorUI.BitCheckbox.OnParametersSetAsync() in /home/runner/work/bitplatform/bitplatform/src/BlazorUI/Bit.BlazorUI/Components/Inputs/Checkbox/BitCheckbox.razor.cs:line 129
[DOTNET]          at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
[DOTNET]          at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
[DOTNET]          at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
[DOTNET]       Microsoft.JSInterop.JSException: Could not find 'BitBlazorUI.Utils.setProperty' ('BitBlazorUI' was undefined).
[DOTNET]       Error: Could not find 'BitBlazorUI.Utils.setProperty' ('BitBlazorUI' was undefined).
[DOTNET]           at https://0.0.0.0/_framework/blazor.webview.js:1:540
[DOTNET]           at Array.forEach (<anonymous>)
[DOTNET]           at l.findFunction (https://0.0.0.0/_framework/blazor.webview.js:1:508)
[DOTNET]           at w (https://0.0.0.0/_framework/blazor.webview.js:1:5251)
[DOTNET]           at https://0.0.0.0/_framework/blazor.webview.js:1:3044
[DOTNET]           at new Promise (<anonymous>)
[DOTNET]           at g.beginInvokeJSFromDotNet (https://0.0.0.0/_framework/blazor.webview.js:1:3007)
[DOTNET]           at External.__callback (https://0.0.0.0/_framework/blazor.webview.js:1:48020)
[DOTNET]           at MessagePort.<anonymous> (<anonymous>:23:21)
[DOTNET]          at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
[DOTNET]          at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
[DOTNET]          at Bit.BlazorUI.BitCheckbox.OnParametersSetAsync() in /home/runner/work/bitplatform/bitplatform/src/BlazorUI/Bit.BlazorUI/Components/Inputs/Checkbox/BitCheckbox.razor.cs:line 129
[DOTNET]          at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
[DOTNET]          at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
[DOTNET]          at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

### .NET Version

8.0

**Comment by msynk** [comment]
Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment]
@mr-farzam sry for the very late reply. are you still encountering this problem?

**Comment by mr-farzam** [comment]
> @mr-farzam sry for the very late reply. are you still encountering this problem?

Thanks. I don't have system these days, I will check and let you.

**Comment by ysmoradi** [comment]
The Android emulator's WebView is often outdated. You'll notice this when our new validation check detects that the WebView version on your device—whether a phone or an emulator—doesn't meet the minimum requirement.
