### ISSUE TITLE
Error while using BitChart

### ISSUE THREAD

**Issue by NileshPhalke123** [bitfoundation/bitplatform#8368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Chart is not defined
ReferenceError: Chart is not defined
    at n (https://0.0.0.0/_content/Bit.BlazorUI.Extras/scripts/bit.blazorui.extras.js:1:4162)
    at t.wireUpOptionsOnClick (https://0.0.0.0/_content/Bit.BlazorUI.Extras/scripts/bit.blazorui.extras.js:1:4320)
    at t.wireUpCallbacks (https://0.0.0.0/_content/Bit.BlazorUI.Extras/scripts/bit.blazorui.extras.js:1:3924)
    at t.setupChart (https://0.0.0.0/_content/Bit.BlazorUI.Extras/scripts/bit.blazorui.extras.js:1:2863)
    at https://0.0.0.0/_framework/blazor.webview.js:1:3050
    at new Promise (<anonymous>)
    at g.beginInvokeJSFromDotNet (https://0.0.0.0/_framework/blazor.webview.js:1:3007)
    at https://0.0.0.0/_framework/blazor.webview.js:1:48020
    at EventTarget.<anonymous> (<anonymous>:7:62)
    at EmbeddedBrowserWebView.<anonymous> (<anonymous>:1:43721)

**Comment by msynk** [comment]
@NileshPhalke123 Thanks for contacting us. We're investigating this issue.
We'll let you know if it's possible to work on this issue.

**Comment by msynk** [comment]
by the exception content that you've provided, it seems the `chartjs` script has not been initialized there.
could you plz share the source code so we can investigate the problem further?
a GitHub repo that can reproduce this problem would be the best option for us to research this error.

**Comment by msynk** [comment]
Since there has been no activity here for a long time, I'm closing this issue.
