### ISSUE TITLE
JSON Value could not be converted to GenericList [Dto type]

### ISSUE THREAD

**Issue by rabeckmann** [bitfoundation/bitplatform#8438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Exception with Boilerplate code v-8.11.0-pre-01, in `ProductsCountPerCategoryWidget`, where `GetProductsCountPerCategoryStats` is called.

```cs
public async Task<List<ProductPercentagePerCategoryResponseDto>> GetProductsPercentagePerCategoryStats(CancellationToken cancellationToken)
{
    var productsTotalCount = await DbContext.Products.CountAsync(cancellationToken);

    if (productsTotalCount == 0)
    {
        return [];
    }

    return await DbContext.Categories
         .Select(c => new ProductPercentagePerCategoryResponseDto()
         {
             CategoryName = c!.Name,
             CategoryColor = c.Color,
             ProductPercentage = (float)decimal.Divide(c.Products!.Count(), productsTotalCount) * 100
         }).ToListAsync(cancellationToken);
}
```

The interface function is declared:

```cs
Task<List<ProductPercentagePerCategoryResponseDto>> GetProductsPercentagePerCategoryStats(CancellationToken cancellationToken);`
```

The `GetData` function in `ProductsCountPerCategoryWidget.cs`:

```cs
private async Task GetData()
{
    try
    {
        isLoading = true;

        var data = await dashboardController.GetProductsCountPerCategoryStats(CurrentCancellationToken);

        BitChartBarDataset<int> chartDataSet = [.. data.Select(d => d.ProductCount)];
        chartDataSet.BackgroundColor = data.Select(d => d.CategoryColor ?? string.Empty).ToArray();
        config.Data.Datasets.Add(chartDataSet);
        config.Data.Labels.AddRange(data.Select(d => d.CategoryName ?? string.Empty));
    }
    finally
    {
        isLoading = false;
    }
}
```

Please help me understand where Json Exception is coming from

### Exceptions (if any)

```
System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.List`1[PrivateRent.Shared.Dtos.Dashboard.ProductPercentagePerCategoryResponseDto]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, JsonTypeInfo`1 jsonTypeInfo, CancellationToken cancellationToken)
   at Microsoft.Extensions.DependencyInjection.IHttpClientServiceCollectionExtensions.DashboardController.<>c__DisplayClass7_0.<<GetProductsPercentagePerCategoryStats>b__0>d.MoveNext() in D:\RAB\PrivateRent\src\Shared\Bit.SourceGenerators\Bit.SourceGenerators.HttpClientProxySourceGenerator\HttpClientProxy.cs:line 316
--- End of stack trace from previous location ---
   at PrivateRent.Client.Core.Services.PrerenderStateService.GetValue[T](String key, Func`1 factory) in D:\RAB\PrivateRent\src\Client\PrivateRent.Client.Core\Services\PrerenderStateService.cs:line 40
   at Microsoft.Extensions.DependencyInjection.IHttpClientServiceCollectionExtensions.DashboardController.GetProductsPercentagePerCategoryStats(CancellationToken cancellationToken) in D:\RAB\PrivateRent\src\Shared\Bit.SourceGenerators\Bit.SourceGenerators.HttpClientProxySourceGenerator\HttpClientProxy.cs:line 303
   at PrivateRent.Client.Core.Components.Pages.Dashboard.ProductsPercentageWidget.GetData() in D:\RAB\PrivateRent\src\Client\PrivateRent.Client.Core\Components\Pages\Dashboard\ProductsPercentageWidget.razor.cs:line 31
   at PrivateRent.Client.Core.Components.Pages.Dashboard.ProductsPercentageWidget.OnInitAsync() in D:\RAB\PrivateRent\src\Client\PrivateRent.Client.Core\Components\Pages\Dashboard\ProductsPercentageWidget.razor.cs:line 22
   at PrivateRent.Client.Core.Components.AppComponentBase.OnInitializedAsync() in D:\RAB\PrivateRent\src\Client\PrivateRent.Client.Core\Components\AppComponentBase.cs:line 58
   ```

_No response_

### .NET Version

8.0.400

### Anything else?

Please note, that I did get the Dashboard working by changing the code as follows, but it's basically taking out async functionality, but haven't managed tog get my own controllers working, so would really appreciate some guidance to where things my be going wrong. 

```cs
public IQueryable<ProductPercentagePerCategoryResponseDto> GetProductsPercentagePerCategoryStats()
{
    var productsTotalCount = DbContext.Products.Count();

    if (productsTotalCount == 0)
    {
        return default;
    }

    return DbContext.Categories
         .Select(c => new ProductPercentagePerCategoryResponseDto()
         {
             CategoryName = c!.Name,
             CategoryColor = c.Color,
             ProductPercentage = (float)decimal.Divide(c.Products!.Count(), productsTotalCount) * 100
         });
}
```

```cs
Task<List<ProductPercentagePerCategoryResponseDto>> GetProductsPercentagePerCategoryStats(CancellationToken cancellationToken) => default!;`
```

Thanks very much

**Comment by ysmoradi** [comment]
Please format the issue, it's really hard to read )":

**Comment by rabeckmann** [comment]
I hope the above makes more sense now? Error occurs on the Dashboard where data is retrieved for the GetProductsPercentagePerCategory widget. I included the code that applies

**Comment by ysmoradi** [comment]
It's still shitty, anyway, could you please let me know if the problem exists from the very beginning of project creation? Or you changed something (for example by setting `PrerenderEnabled` to true in `AppRenderMode.cs`?) and then you faced such a problem?
I say this, because we're publishing Boilerplate regularly on https://adminpanel.bitplatform.dev and I don't see such a problem there.

**Comment by rabeckmann** [comment]
Ok, then I suppose I can not make the description of the issue less "shitty". 

Been checking to see if we can use this platform for a week or so and may probably changed something that could have  broken this, because the code in the widget has not changed.

But if you can't give me an idea where things may be going wrong, so be it. Thanks anyway

**Comment by ysmoradi** [comment]
I just formatted the issue, and you didn't answer the question, have you changed something? or project is broken from the very beginning after you create it using dotnet new?

**Comment by ysmoradi** [comment]
And not that returning `IQueryable` doesn't mean your code is not async! Because the query returned by ef core is implementing `IAsyncEnumerable` which is supported by aspnetcore at the same time. In fact, it's more performant, due the fact that aspnetcore streams response to the client instead of buffering the whole result into a list.

**Comment by rabeckmann** [comment]
Thanks for the info.

Had to do some history comparing ;)

Seems like I had changed the AddControllers like this, as I battled a bit with Mapperly:

services
    .AddControllers().AddJsonOptions(x => x.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.Preserve)

Undoing the AddJsonOptions fixed it.

**Comment by ysmoradi** [comment]
Glad to hear that! Let us know if you encountered any issues.
