### ISSUE TITLE
Culture change produces JS exception in Maui Win & Android

### ISSUE THREAD

**Issue by techscx** [bitfoundation/bitplatform#8715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On some pages, e.g. profile page, changing the culture produces a JS exception in Maui Win & Android. The app is then sitting in the LoadingComponent without showing any content and not finishing the loading of the page.

### Expected Behavior

There shouldn't be an exception.

### Steps To Reproduce

- Install admin template from android playstore or install the app via visual studio on android or on windows.
- navigate to profile page
- change the culture  

### Exceptions (if any)

Visual Studio Debugger: No exception thrown.
Browser debug console:
blazor.webview.js:1  JS object instance with ID 1 does not exist (has it been disposed?).
Error: JS object instance with ID 1 does not exist (has it been disposed?).
    at w (https://0.0.0.0/_framework/blazor.webview.js:1:5273)
    at https://0.0.0.0/_framework/blazor.webview.js:1:3044
    at new Promise (<anonymous>)
    at g.beginInvokeJSFromDotNet (https://0.0.0.0/_framework/blazor.webview.js:1:3007)
    at https://0.0.0.0/_framework/blazor.webview.js:1:48020
    at EventTarget.<anonymous> (<anonymous>:7:62)
    at EmbeddedBrowserWebView.<anonymous> (<anonymous>:1:43835)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at Bit.BlazorUI.BitFileUpload.DisposeAsync(Boolean disposing)
   at Bit.BlazorUI.BitFileUpload.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass85_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
NotifyUnhandledException @ blazor.webview.js:1
(anonymous) @ blazor.webview.js:1
(anonymous) @ VM15:7
(anonymous) @ VM14:1

### .NET Version

8.0.400

**Comment by ysmoradi** [comment]
Could you please let me know what's the version of the app you've installed from Google Play? You can see version in about page.
And On which Android version / which specific device you're getting this error?

**Comment by techscx** [comment]
By now i get the error on IOS as well.

Windows:
bitplatform 8.11.0
Application running both in dev and release mode from visual studio.
NET 8.

IOS:
Iphone 15 Prox Max
IOS 18.0
Iphone 15
IOS 17.6.1
both and others running adminpanel 117.0.0

Android:
Pixel 6
Android 14
adminpanel 117.0.0

**Comment by techscx** [comment]
Were you able to reproduce the behaviour?

> Could you please let me know what's the version of the app you've installed from Google Play? You can see version in about page. And On which Android version / which specific device you're getting this error?

**Comment by ysmoradi** [comment]
We've improved culture management recently, wait for the new pre-release

**Comment by msynk** [comment]
this issue is now resolved.
